[package]
name = "tui-components"
version = "0.1.0"
authors = ["BenHall-7 <Benjaminjahall@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
tui = { version = "0.16.0", features = ["crossterm"] }
crossterm = "0.20"
